#pragma once
#ifndef CONFIGURATION
#define CONFIGURATION

//#define CEREBRAL_VESSELS
//#define MANUAL_SEGMENTATION 

#define PRINT_LOG_INTEROP 
//#define PRINT_BRANCHES
#define PRINT_CENTERLINE

//#define CONNECT_TO_NODE
#define CONNECT_TO_RIB_POINT
#define USE_ONLY_DIST

#define MASK_FOR_VESSELNESS
//#define NONVESSELNESS_FROM_FILE
//#define CUT_DECSENDING_AORTA

//#define SKIP_AORTA
//#define MANUAL_SEGMENTATION

//#define PRINT_AORTA_VTB
//#define PRINT_AORTA
#define PRINT_AORTA_SURFACE
#define PRINT_LOG_VTB
#define PRINT_LOGS_GRAPH


//#define PERIVASCULAR

#endif // CONFIGURATION