#ifndef ARTERIALTREEBUILDERDLL_GLOBAL_H
#define ARTERIALTREEBUILDERDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ARTERIALTREEBUILDERDLL_LIBRARY)
#  define ARTERIALTREEBUILDERDLL_EXPORT Q_DECL_EXPORT
#else
#  define ARTERIALTREEBUILDERDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // ARTERIALTREEBUILDERDLL_GLOBAL_H
