# Создание контейнера cradle/u:base 238 сек 500M
# docker build - --tag cradle/u:0 < ./scripts/Dockerfile.u.0
# 
FROM ubuntu:21.04
ENV TZ=Europe/Kaliningrad
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update && apt-get install -y build-essential cmake wget git



