# Создание контейнера cradle/u:1 == u:0+ITK-5.1
# docker build - --tag cradle/u:1 < ./scripts/Dockerfile.u.1
#
FROM cradle/u:0

# Поменяли версию на 5.3.0 c 5.1.0 из-за ошибки компиляции (см. ниже)

ARG ITK_VERSION=5.3.0
RUN mkdir -p /pkgs/src/ITK-${ITK_VERSION}-build && cd /pkgs/src \
 && wget https://github.com/InsightSoftwareConsortium/ITK/releases/download/v${ITK_VERSION}/InsightToolkit-${ITK_VERSION}.tar.gz \
 && tar xzf InsightToolkit-${ITK_VERSION}.tar.gz && cd ITK-${ITK_VERSION}-build \
 && cmake -DModule_IOMeshSTL=ON -DCMAKE_BUILD_TYPE=Release ../InsightToolkit-${ITK_VERSION} \
 && make install && cd / && rm -r /pkgs/src

 ## 1340 сек 633M /usr/local/include/ITK-5.3; /usr/local/lib/lib*-5.3.a

# Built target ITKTestKernel (5.1.0)
#5 852.1 Scanning dependencies of target itkTestDriver
#5 852.1 [ 99%] Building CXX object Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/itkTestDriver.cxx.o
#5 852.9 [ 99%] Linking CXX executable ../../../../bin/itkTestDriver
#5 853.2 ../../../../lib/libitkpng-5.1.a(pngrtran.c.o):pngrtran.c:function itk_png_do_read_transformations: error: undefined reference to 'png_do_expand_palette_rgba8_neon'
#5 853.2 ../../../../lib/libitkpng-5.1.a(pngrtran.c.o):pngrtran.c:function itk_png_do_read_transformations: error: undefined reference to 'png_riffle_palette_neon'
#5 853.2 ../../../../lib/libitkpng-5.1.a(pngrtran.c.o):pngrtran.c:function itk_png_do_read_transformations: error: undefined reference to 'png_do_expand_palette_rgb8_neon'
#5 853.2 ../../../../lib/libitkpng-5.1.a(pngrutil.c.o):pngrutil.c:function itk_png_read_filter_row: error: undefined reference to 'png_init_filter_functions_neon'
#5 853.2 collect2: error: ld returned 1 exit status
#5 853.2 make[2]: *** [Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/build.make:154: bin/itkTestDriver] Error 1
#5 853.2 make[1]: *** [CMakeFiles/Makefile2:13749: Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/all] Error 2
#5 853.2 make: *** [Makefile:152: all] Error 2