name: Virtual Endoscopy.Deploy app
run-name: Try to deploy latest version
on:
  workflow_run:
    workflows: [Virtual Endoscopy.Test app]
    types: [completed]
    branches: [main]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: builtServer
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./builtServer/*"
          target: ./builtServer
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: /bin/bash restart.sh
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The tests were failed. Deployment canceled.'; exit 1;