name: Virtual Endoscopy.Deploy app.Step 2
run-name: ${{ github.actor }} started deploy. Version ${{ inputs && inputs.version || 'latest' }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version that will be deployed'
        default: ''
        required: false
        type: string
  push:
    branches:
      - 'main'
jobs:
  Test_app:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-tag
        name: Checkout repository by tag
        if: ${{ inputs && inputs.version != '' }}
        uses: actions/checkout@v3
        with:
          ref: tags/${{ inputs.version }}
      - id: checkout-latest
        name: Checkout repository by latest commit
        if: ${{ steps.checkout-tag.status != 'success' }}
        uses: actions/checkout@v3
      - id: go-setup
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - id: node-setup
        name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - id: cache
        name: Use cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('./web/package-lock.json') }}
      - id: dependencies-install
        name: Install dependencies
        working-directory: ./web
        run: npm ci
      - id: app-build
        name: Build app
        working-directory: ./web
        run: npm run build
      - id: artifact-upload
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: builtServer
          path: ./builtServer